# Production configuration for the Energy Price API
services:
  price-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: energy-price-api:latest
    container_name: energy-price-api-prod
    ports:
      - "8000:8000"
    volumes:
      - price_data:/app/data
      - price_logs:/app/logs
    env_file:
      - .env
    environment:
      # Production-specific overrides
      - API_HOST=0.0.0.0
      - API_DEBUG=false
      - API_RELOAD=false
      - DATABASE_PATH=/app/data/prices.db
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-m", "src.health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - price-api-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

# Named volumes with backup-friendly configuration
volumes:
  price_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  price_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

# Network for service isolation
networks:
  price-api-network:
    driver: bridge
